# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    env:
      TMP_DIR: /home/kodiyak/projects/files/tmp-matrix-adonis

    strategy:
      matrix:
        node-version: [14.15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check Tmp File
        id: check_tmp_files
        uses: andstor/file-existence-action@v1
        with:
          files: './build/tmp'

      - name: File exists
        if: steps.check_tmp_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: mv ./build/tmp ${{ env.TMP_DIR }}

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --fronzen-lockfile

      - name: Build Application
        run: yarn build

      - name: Install Production Dependencies
        working-directory: ./build
        run: yarn install --production

      - name: Copy Env
        working-directory: ./build
        run: cp /home/kodiyak/projects/envs/.env-matrix-adonis-crm .env

      - name: Moving Tmp Files
        run: mv ${{ env.TMP_DIR }} ./build/tmp

      - run: sudo chmod 777 -R ./build/tmp

      - name: Stop pm2
        run: pm2 delete MatrixCrmBackend
        if: ${{failure()}}

      - name: Start pm2
        working-directory: ./build
        run: pm2 start server.js --name MatrixCrmBackend -f
